# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/player/daily_counter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/player/daily_counter.proto',
  package='pogoprotos.data.player',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n*pogoprotos/data/player/daily_counter.proto\x12\x16pogoprotos.data.player\"-\n\x0c\x44\x61ilyCounter\x12\x0e\n\x06window\x18\x01 \x01(\x03\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x62\x06proto3')
)




_DAILYCOUNTER = _descriptor.Descriptor(
  name='DailyCounter',
  full_name='pogoprotos.data.player.DailyCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='window', full_name='pogoprotos.data.player.DailyCounter.window', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='pogoprotos.data.player.DailyCounter.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['DailyCounter'] = _DAILYCOUNTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DailyCounter = _reflection.GeneratedProtocolMessageType('DailyCounter', (_message.Message,), dict(
  DESCRIPTOR = _DAILYCOUNTER,
  __module__ = 'pogoprotos.data.player.daily_counter_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.player.DailyCounter)
  ))
_sym_db.RegisterMessage(DailyCounter)


# @@protoc_insertion_point(module_scope)
