# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/ar_context.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/enums/ar_context.proto',
  package='pogoprotos.enums',
  syntax='proto3',
  serialized_pb=_b('\n!pogoprotos/enums/ar_context.proto\x12\x10pogoprotos.enums*\x1a\n\tArContext\x12\r\n\tENCOUNTER\x10\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ARCONTEXT = _descriptor.EnumDescriptor(
  name='ArContext',
  full_name='pogoprotos.enums.ArContext',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENCOUNTER', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=55,
  serialized_end=81,
)
_sym_db.RegisterEnumDescriptor(_ARCONTEXT)

ArContext = enum_type_wrapper.EnumTypeWrapper(_ARCONTEXT)
ENCOUNTER = 0


DESCRIPTOR.enum_types_by_name['ArContext'] = _ARCONTEXT


# @@protoc_insertion_point(module_scope)
