# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/ar_plus_mode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/enums/ar_plus_mode.proto',
  package='pogoprotos.enums',
  syntax='proto3',
  serialized_pb=_b('\n#pogoprotos/enums/ar_plus_mode.proto\x12\x10pogoprotos.enums*,\n\nArPlusMode\x12\n\n\x06\x41RPLUS\x10\x00\x12\x06\n\x02\x41R\x10\x01\x12\n\n\x06NORMAL\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ARPLUSMODE = _descriptor.EnumDescriptor(
  name='ArPlusMode',
  full_name='pogoprotos.enums.ArPlusMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARPLUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=57,
  serialized_end=101,
)
_sym_db.RegisterEnumDescriptor(_ARPLUSMODE)

ArPlusMode = enum_type_wrapper.EnumTypeWrapper(_ARPLUSMODE)
ARPLUS = 0
AR = 1
NORMAL = 2


DESCRIPTOR.enum_types_by_name['ArPlusMode'] = _ARPLUSMODE


# @@protoc_insertion_point(module_scope)
