# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/decline_ex_raid_pass_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/decline_ex_raid_pass_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nCpogoprotos/networking/responses/decline_ex_raid_pass_response.proto\x12\x1fpogoprotos.networking.responses\"\xc5\x01\n\x19\x44\x65\x63lineExRaidPassResponse\x12Q\n\x06result\x18\x01 \x01(\x0e\x32\x41.pogoprotos.networking.responses.DeclineExRaidPassResponse.Result\"U\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12 \n\x1c\x45RROR_EX_RAID_PASS_NOT_FOUND\x10\x02\x12\x11\n\rERROR_UNKNOWN\x10\x03\x62\x06proto3')
)



_DECLINEEXRAIDPASSRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.networking.responses.DeclineExRaidPassResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_EX_RAID_PASS_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNKNOWN', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=217,
  serialized_end=302,
)
_sym_db.RegisterEnumDescriptor(_DECLINEEXRAIDPASSRESPONSE_RESULT)


_DECLINEEXRAIDPASSRESPONSE = _descriptor.Descriptor(
  name='DeclineExRaidPassResponse',
  full_name='pogoprotos.networking.responses.DeclineExRaidPassResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.networking.responses.DeclineExRaidPassResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DECLINEEXRAIDPASSRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=302,
)

_DECLINEEXRAIDPASSRESPONSE.fields_by_name['result'].enum_type = _DECLINEEXRAIDPASSRESPONSE_RESULT
_DECLINEEXRAIDPASSRESPONSE_RESULT.containing_type = _DECLINEEXRAIDPASSRESPONSE
DESCRIPTOR.message_types_by_name['DeclineExRaidPassResponse'] = _DECLINEEXRAIDPASSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeclineExRaidPassResponse = _reflection.GeneratedProtocolMessageType('DeclineExRaidPassResponse', (_message.Message,), dict(
  DESCRIPTOR = _DECLINEEXRAIDPASSRESPONSE,
  __module__ = 'pogoprotos.networking.responses.decline_ex_raid_pass_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.DeclineExRaidPassResponse)
  ))
_sym_db.RegisterMessage(DeclineExRaidPassResponse)


# @@protoc_insertion_point(module_scope)
