# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/fitness_update_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/fitness_update_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n=pogoprotos/networking/responses/fitness_update_response.proto\x12\x1fpogoprotos.networking.responses\"\x9b\x01\n\x15\x46itnessUpdateResponse\x12M\n\x06status\x18\x01 \x01(\x0e\x32=.pogoprotos.networking.responses.FitnessUpdateResponse.Status\"3\n\x06Status\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x11\n\rERROR_UNKNOWN\x10\x02\x62\x06proto3')
)



_FITNESSUPDATERESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pogoprotos.networking.responses.FitnessUpdateResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNKNOWN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=203,
  serialized_end=254,
)
_sym_db.RegisterEnumDescriptor(_FITNESSUPDATERESPONSE_STATUS)


_FITNESSUPDATERESPONSE = _descriptor.Descriptor(
  name='FitnessUpdateResponse',
  full_name='pogoprotos.networking.responses.FitnessUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pogoprotos.networking.responses.FitnessUpdateResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FITNESSUPDATERESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=254,
)

_FITNESSUPDATERESPONSE.fields_by_name['status'].enum_type = _FITNESSUPDATERESPONSE_STATUS
_FITNESSUPDATERESPONSE_STATUS.containing_type = _FITNESSUPDATERESPONSE
DESCRIPTOR.message_types_by_name['FitnessUpdateResponse'] = _FITNESSUPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FitnessUpdateResponse = _reflection.GeneratedProtocolMessageType('FitnessUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _FITNESSUPDATERESPONSE,
  __module__ = 'pogoprotos.networking.responses.fitness_update_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.FitnessUpdateResponse)
  ))
_sym_db.RegisterMessage(FitnessUpdateResponse)


# @@protoc_insertion_point(module_scope)
