# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/geofence_update_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data import geofence_metadata_pb2 as pogoprotos_dot_data_dot_geofence__metadata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/geofence_update_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n>pogoprotos/networking/responses/geofence_update_response.proto\x12\x1fpogoprotos.networking.responses\x1a\'pogoprotos/data/geofence_metadata.proto\"M\n\x16GeofenceUpdateResponse\x12\x33\n\x08geofence\x18\x01 \x03(\x0b\x32!.pogoprotos.data.GeofenceMetadatab\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_geofence__metadata__pb2.DESCRIPTOR,])




_GEOFENCEUPDATERESPONSE = _descriptor.Descriptor(
  name='GeofenceUpdateResponse',
  full_name='pogoprotos.networking.responses.GeofenceUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geofence', full_name='pogoprotos.networking.responses.GeofenceUpdateResponse.geofence', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=217,
)

_GEOFENCEUPDATERESPONSE.fields_by_name['geofence'].message_type = pogoprotos_dot_data_dot_geofence__metadata__pb2._GEOFENCEMETADATA
DESCRIPTOR.message_types_by_name['GeofenceUpdateResponse'] = _GEOFENCEUPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeofenceUpdateResponse = _reflection.GeneratedProtocolMessageType('GeofenceUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _GEOFENCEUPDATERESPONSE,
  __module__ = 'pogoprotos.networking.responses.geofence_update_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.GeofenceUpdateResponse)
  ))
_sym_db.RegisterMessage(GeofenceUpdateResponse)


# @@protoc_insertion_point(module_scope)
