# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/get_background_mode_settings_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.settings import background_mode_client_settings_pb2 as pogoprotos_dot_settings_dot_background__mode__client__settings__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/get_background_mode_settings_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nKpogoprotos/networking/responses/get_background_mode_settings_response.proto\x12\x1fpogoprotos.networking.responses\x1a\x39pogoprotos/settings/background_mode_client_settings.proto\"\xf8\x01\n!GetBackgroundModeSettingsResponse\x12Y\n\x06status\x18\x01 \x01(\x0e\x32I.pogoprotos.networking.responses.GetBackgroundModeSettingsResponse.Status\x12\x43\n\x08settings\x18\x02 \x01(\x0b\x32\x31.pogoprotos.settings.BackgroundModeClientSettings\"3\n\x06Status\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x11\n\rERROR_UNKNOWN\x10\x02\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_settings_dot_background__mode__client__settings__pb2.DESCRIPTOR,])



_GETBACKGROUNDMODESETTINGSRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pogoprotos.networking.responses.GetBackgroundModeSettingsResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNKNOWN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=369,
  serialized_end=420,
)
_sym_db.RegisterEnumDescriptor(_GETBACKGROUNDMODESETTINGSRESPONSE_STATUS)


_GETBACKGROUNDMODESETTINGSRESPONSE = _descriptor.Descriptor(
  name='GetBackgroundModeSettingsResponse',
  full_name='pogoprotos.networking.responses.GetBackgroundModeSettingsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pogoprotos.networking.responses.GetBackgroundModeSettingsResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settings', full_name='pogoprotos.networking.responses.GetBackgroundModeSettingsResponse.settings', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETBACKGROUNDMODESETTINGSRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=420,
)

_GETBACKGROUNDMODESETTINGSRESPONSE.fields_by_name['status'].enum_type = _GETBACKGROUNDMODESETTINGSRESPONSE_STATUS
_GETBACKGROUNDMODESETTINGSRESPONSE.fields_by_name['settings'].message_type = pogoprotos_dot_settings_dot_background__mode__client__settings__pb2._BACKGROUNDMODECLIENTSETTINGS
_GETBACKGROUNDMODESETTINGSRESPONSE_STATUS.containing_type = _GETBACKGROUNDMODESETTINGSRESPONSE
DESCRIPTOR.message_types_by_name['GetBackgroundModeSettingsResponse'] = _GETBACKGROUNDMODESETTINGSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetBackgroundModeSettingsResponse = _reflection.GeneratedProtocolMessageType('GetBackgroundModeSettingsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETBACKGROUNDMODESETTINGSRESPONSE,
  __module__ = 'pogoprotos.networking.responses.get_background_mode_settings_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.GetBackgroundModeSettingsResponse)
  ))
_sym_db.RegisterMessage(GetBackgroundModeSettingsResponse)


# @@protoc_insertion_point(module_scope)
