# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/telemetry/platform_event_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.networking.platform.telemetry import telemetry_common_pb2 as pogoprotos_dot_networking_dot_platform_dot_telemetry_dot_telemetry__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/platform/telemetry/platform_event_data.proto',
  package='pogoprotos.networking.platform.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nBpogoprotos/networking/platform/telemetry/platform_event_data.proto\x12(pogoprotos.networking.platform.telemetry\x1a?pogoprotos/networking/platform/telemetry/telemetry_common.proto\"h\n\x11PlatformEventData\x12S\n\x10\x63ommon_telemetry\x18\x01 \x01(\x0b\x32\x39.pogoprotos.networking.platform.telemetry.TelemetryCommonb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_networking_dot_platform_dot_telemetry_dot_telemetry__common__pb2.DESCRIPTOR,])




_PLATFORMEVENTDATA = _descriptor.Descriptor(
  name='PlatformEventData',
  full_name='pogoprotos.networking.platform.telemetry.PlatformEventData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_telemetry', full_name='pogoprotos.networking.platform.telemetry.PlatformEventData.common_telemetry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=281,
)

_PLATFORMEVENTDATA.fields_by_name['common_telemetry'].message_type = pogoprotos_dot_networking_dot_platform_dot_telemetry_dot_telemetry__common__pb2._TELEMETRYCOMMON
DESCRIPTOR.message_types_by_name['PlatformEventData'] = _PLATFORMEVENTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlatformEventData = _reflection.GeneratedProtocolMessageType('PlatformEventData', (_message.Message,), dict(
  DESCRIPTOR = _PLATFORMEVENTDATA,
  __module__ = 'pogoprotos.networking.platform.telemetry.platform_event_data_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.platform.telemetry.PlatformEventData)
  ))
_sym_db.RegisterMessage(PlatformEventData)


# @@protoc_insertion_point(module_scope)
