# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/telemetry/platform_data_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.networking.platform.telemetry import telemetry_domain_id_pb2 as pogoprotos_dot_networking_dot_platform_dot_telemetry_dot_telemetry__domain__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/platform/telemetry/platform_data_id.proto',
  package='pogoprotos.networking.platform.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n?pogoprotos/networking/platform/telemetry/platform_data_id.proto\x12(pogoprotos.networking.platform.telemetry\x1a\x42pogoprotos/networking/platform/telemetry/telemetry_domain_id.proto\"\x80\x01\n\x0ePlatformDataId\x12\x14\n\x0ctelemetry_id\x18\x01 \x01(\x05\x12X\n\x13telemetry_domain_id\x18\x02 \x01(\x0e\x32;.pogoprotos.networking.platform.telemetry.TelemetryDomainIdb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_networking_dot_platform_dot_telemetry_dot_telemetry__domain__id__pb2.DESCRIPTOR,])




_PLATFORMDATAID = _descriptor.Descriptor(
  name='PlatformDataId',
  full_name='pogoprotos.networking.platform.telemetry.PlatformDataId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='telemetry_id', full_name='pogoprotos.networking.platform.telemetry.PlatformDataId.telemetry_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='telemetry_domain_id', full_name='pogoprotos.networking.platform.telemetry.PlatformDataId.telemetry_domain_id', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=306,
)

_PLATFORMDATAID.fields_by_name['telemetry_domain_id'].enum_type = pogoprotos_dot_networking_dot_platform_dot_telemetry_dot_telemetry__domain__id__pb2._TELEMETRYDOMAINID
DESCRIPTOR.message_types_by_name['PlatformDataId'] = _PLATFORMDATAID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlatformDataId = _reflection.GeneratedProtocolMessageType('PlatformDataId', (_message.Message,), dict(
  DESCRIPTOR = _PLATFORMDATAID,
  __module__ = 'pogoprotos.networking.platform.telemetry.platform_data_id_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.platform.telemetry.PlatformDataId)
  ))
_sym_db.RegisterMessage(PlatformDataId)


# @@protoc_insertion_point(module_scope)
