# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/social/get_incoming_friend_invites_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/social/get_incoming_friend_invites_message.proto',
  package='pogoprotos.networking.requests.social',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nOpogoprotos/networking/requests/social/get_incoming_friend_invites_message.proto\x12%pogoprotos.networking.requests.social\"!\n\x1fGetIncomingFriendInvitesMessageb\x06proto3')
)




_GETINCOMINGFRIENDINVITESMESSAGE = _descriptor.Descriptor(
  name='GetIncomingFriendInvitesMessage',
  full_name='pogoprotos.networking.requests.social.GetIncomingFriendInvitesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['GetIncomingFriendInvitesMessage'] = _GETINCOMINGFRIENDINVITESMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetIncomingFriendInvitesMessage = _reflection.GeneratedProtocolMessageType('GetIncomingFriendInvitesMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETINCOMINGFRIENDINVITESMESSAGE,
  __module__ = 'pogoprotos.networking.requests.social.get_incoming_friend_invites_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.social.GetIncomingFriendInvitesMessage)
  ))
_sym_db.RegisterMessage(GetIncomingFriendInvitesMessage)


# @@protoc_insertion_point(module_scope)
