# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/social/get_friends_list_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/social/get_friends_list_message.proto',
  package='pogoprotos.networking.requests.social',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nDpogoprotos/networking/requests/social/get_friends_list_message.proto\x12%pogoprotos.networking.requests.social\"\x17\n\x15GetFriendsListMessageb\x06proto3')
)




_GETFRIENDSLISTMESSAGE = _descriptor.Descriptor(
  name='GetFriendsListMessage',
  full_name='pogoprotos.networking.requests.social.GetFriendsListMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['GetFriendsListMessage'] = _GETFRIENDSLISTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFriendsListMessage = _reflection.GeneratedProtocolMessageType('GetFriendsListMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETFRIENDSLISTMESSAGE,
  __module__ = 'pogoprotos.networking.requests.social.get_friends_list_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.social.GetFriendsListMessage)
  ))
_sym_db.RegisterMessage(GetFriendsListMessage)


# @@protoc_insertion_point(module_scope)
