# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/social/list_outgoing_friend_invites_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/social/list_outgoing_friend_invites_message.proto',
  package='pogoprotos.networking.requests.social',
  syntax='proto3',
  serialized_pb=_b('\nPpogoprotos/networking/requests/social/list_outgoing_friend_invites_message.proto\x12%pogoprotos.networking.requests.social\"\"\n ListOutgoingFriendInvitesMessageb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LISTOUTGOINGFRIENDINVITESMESSAGE = _descriptor.Descriptor(
  name='ListOutgoingFriendInvitesMessage',
  full_name='pogoprotos.networking.requests.social.ListOutgoingFriendInvitesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['ListOutgoingFriendInvitesMessage'] = _LISTOUTGOINGFRIENDINVITESMESSAGE

ListOutgoingFriendInvitesMessage = _reflection.GeneratedProtocolMessageType('ListOutgoingFriendInvitesMessage', (_message.Message,), dict(
  DESCRIPTOR = _LISTOUTGOINGFRIENDINVITESMESSAGE,
  __module__ = 'pogoprotos.networking.requests.social.list_outgoing_friend_invites_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.social.ListOutgoingFriendInvitesMessage)
  ))
_sym_db.RegisterMessage(ListOutgoingFriendInvitesMessage)


# @@protoc_insertion_point(module_scope)
