# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/social/get_friends_list_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/social/get_friends_list_response.proto',
  package='pogoprotos.networking.responses.social',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nFpogoprotos/networking/responses/social/get_friends_list_response.proto\x12&pogoprotos.networking.responses.social\"\xb7\x03\n\x16GetFriendsListResponse\x12U\n\x06result\x18\x01 \x01(\x0e\x32\x45.pogoprotos.networking.responses.social.GetFriendsListResponse.Result\x12U\n\x06\x66riend\x18\x02 \x03(\x0b\x32\x45.pogoprotos.networking.responses.social.GetFriendsListResponse.Friend\x1a\xb9\x01\n\x06\x46riend\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x10\n\x08\x63odename\x18\x02 \x01(\t\x12\x0c\n\x04team\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x05\x12\x14\n\x0c\x64\x61ta_with_me\x18\x05 \x01(\x0c\x12\x0f\n\x07version\x18\x06 \x01(\x03\x12\x12\n\ncreated_ms\x18\x07 \x01(\x03\x12\x12\n\nfb_user_id\x18\x08 \x01(\t\x12\x1e\n\x16is_facebook_friendship\x18\t \x01(\x08\"3\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x11\n\rERROR_UNKNOWN\x10\x02\x62\x06proto3')
)



_GETFRIENDSLISTRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNKNOWN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=503,
  serialized_end=554,
)
_sym_db.RegisterEnumDescriptor(_GETFRIENDSLISTRESPONSE_RESULT)


_GETFRIENDSLISTRESPONSE_FRIEND = _descriptor.Descriptor(
  name='Friend',
  full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Friend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Friend.player_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codename', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Friend.codename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Friend.team', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Friend.score', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_with_me', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Friend.data_with_me', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Friend.version', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_ms', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Friend.created_ms', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fb_user_id', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Friend.fb_user_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_facebook_friendship', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.Friend.is_facebook_friendship', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=501,
)

_GETFRIENDSLISTRESPONSE = _descriptor.Descriptor(
  name='GetFriendsListResponse',
  full_name='pogoprotos.networking.responses.social.GetFriendsListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='friend', full_name='pogoprotos.networking.responses.social.GetFriendsListResponse.friend', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETFRIENDSLISTRESPONSE_FRIEND, ],
  enum_types=[
    _GETFRIENDSLISTRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=554,
)

_GETFRIENDSLISTRESPONSE_FRIEND.containing_type = _GETFRIENDSLISTRESPONSE
_GETFRIENDSLISTRESPONSE.fields_by_name['result'].enum_type = _GETFRIENDSLISTRESPONSE_RESULT
_GETFRIENDSLISTRESPONSE.fields_by_name['friend'].message_type = _GETFRIENDSLISTRESPONSE_FRIEND
_GETFRIENDSLISTRESPONSE_RESULT.containing_type = _GETFRIENDSLISTRESPONSE
DESCRIPTOR.message_types_by_name['GetFriendsListResponse'] = _GETFRIENDSLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFriendsListResponse = _reflection.GeneratedProtocolMessageType('GetFriendsListResponse', (_message.Message,), dict(

  Friend = _reflection.GeneratedProtocolMessageType('Friend', (_message.Message,), dict(
    DESCRIPTOR = _GETFRIENDSLISTRESPONSE_FRIEND,
    __module__ = 'pogoprotos.networking.responses.social.get_friends_list_response_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.social.GetFriendsListResponse.Friend)
    ))
  ,
  DESCRIPTOR = _GETFRIENDSLISTRESPONSE,
  __module__ = 'pogoprotos.networking.responses.social.get_friends_list_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.social.GetFriendsListResponse)
  ))
_sym_db.RegisterMessage(GetFriendsListResponse)
_sym_db.RegisterMessage(GetFriendsListResponse.Friend)


# @@protoc_insertion_point(module_scope)
