# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/requests/client_telemetry_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.networking.platform.telemetry import platform_data_id_pb2 as pogoprotos_dot_networking_dot_platform_dot_telemetry_dot_platform__data__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/platform/requests/client_telemetry_request.proto',
  package='pogoprotos.networking.platform.requests',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nFpogoprotos/networking/platform/requests/client_telemetry_request.proto\x12\'pogoprotos.networking.platform.requests\x1a?pogoprotos/networking/platform/telemetry/platform_data_id.proto\"v\n\x0f\x43lientTelemetry\x12I\n\x07\x64\x61ta_id\x18\x01 \x03(\x0b\x32\x38.pogoprotos.networking.platform.telemetry.PlatformDataId\x12\x18\n\x10\x61pplication_data\x18\x02 \x03(\x0c\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_networking_dot_platform_dot_telemetry_dot_platform__data__id__pb2.DESCRIPTOR,])




_CLIENTTELEMETRY = _descriptor.Descriptor(
  name='ClientTelemetry',
  full_name='pogoprotos.networking.platform.requests.ClientTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_id', full_name='pogoprotos.networking.platform.requests.ClientTelemetry.data_id', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='application_data', full_name='pogoprotos.networking.platform.requests.ClientTelemetry.application_data', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=298,
)

_CLIENTTELEMETRY.fields_by_name['data_id'].message_type = pogoprotos_dot_networking_dot_platform_dot_telemetry_dot_platform__data__id__pb2._PLATFORMDATAID
DESCRIPTOR.message_types_by_name['ClientTelemetry'] = _CLIENTTELEMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientTelemetry = _reflection.GeneratedProtocolMessageType('ClientTelemetry', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTELEMETRY,
  __module__ = 'pogoprotos.networking.platform.requests.client_telemetry_request_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.platform.requests.ClientTelemetry)
  ))
_sym_db.RegisterMessage(ClientTelemetry)


# @@protoc_insertion_point(module_scope)
