# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/requests/register_downstream_server_actions_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/platform/requests/register_downstream_server_actions_request.proto',
  package='pogoprotos.networking.platform.requests',
  syntax='proto3',
  serialized_pb=_b('\nXpogoprotos/networking/platform/requests/register_downstream_server_actions_request.proto\x12\'pogoprotos.networking.platform.requests\"(\n&RegisterDownstreamServerActionsRequestb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REGISTERDOWNSTREAMSERVERACTIONSREQUEST = _descriptor.Descriptor(
  name='RegisterDownstreamServerActionsRequest',
  full_name='pogoprotos.networking.platform.requests.RegisterDownstreamServerActionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['RegisterDownstreamServerActionsRequest'] = _REGISTERDOWNSTREAMSERVERACTIONSREQUEST

RegisterDownstreamServerActionsRequest = _reflection.GeneratedProtocolMessageType('RegisterDownstreamServerActionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERDOWNSTREAMSERVERACTIONSREQUEST,
  __module__ = 'pogoprotos.networking.platform.requests.register_downstream_server_actions_request_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.platform.requests.RegisterDownstreamServerActionsRequest)
  ))
_sym_db.RegisterMessage(RegisterDownstreamServerActionsRequest)


# @@protoc_insertion_point(module_scope)
