# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/debug_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/debug_info.proto',
  package='pogoprotos.data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n pogoprotos/data/debug_info.proto\x12\x0fpogoprotos.data\"0\n\tDebugInfo\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x62\x06proto3')
)




_DEBUGINFO = _descriptor.Descriptor(
  name='DebugInfo',
  full_name='pogoprotos.data.DebugInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='pogoprotos.data.DebugInfo.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='pogoprotos.data.DebugInfo.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['DebugInfo'] = _DEBUGINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DebugInfo = _reflection.GeneratedProtocolMessageType('DebugInfo', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGINFO,
  __module__ = 'pogoprotos.data.debug_info_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.DebugInfo)
  ))
_sym_db.RegisterMessage(DebugInfo)


# @@protoc_insertion_point(module_scope)
