# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/npc_pokemon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data import pokemon_display_pb2 as pogoprotos_dot_data_dot_pokemon__display__pb2
from pogoprotos.enums import pokemon_id_pb2 as pogoprotos_dot_enums_dot_pokemon__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/npc_pokemon.proto',
  package='pogoprotos.data',
  syntax='proto3',
  serialized_pb=_b('\n!pogoprotos/data/npc_pokemon.proto\x12\x0fpogoprotos.data\x1a%pogoprotos/data/pokemon_display.proto\x1a!pogoprotos/enums/pokemon_id.proto\"y\n\nNpcPokemon\x12\x31\n\x0cpokemon_type\x18\x01 \x01(\x0e\x32\x1b.pogoprotos.enums.PokemonId\x12\x38\n\x0fpokemon_display\x18\x02 \x01(\x0b\x32\x1f.pogoprotos.data.PokemonDisplayb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_pokemon__display__pb2.DESCRIPTOR,pogoprotos_dot_enums_dot_pokemon__id__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NPCPOKEMON = _descriptor.Descriptor(
  name='NpcPokemon',
  full_name='pogoprotos.data.NpcPokemon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokemon_type', full_name='pogoprotos.data.NpcPokemon.pokemon_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokemon_display', full_name='pogoprotos.data.NpcPokemon.pokemon_display', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=249,
)

_NPCPOKEMON.fields_by_name['pokemon_type'].enum_type = pogoprotos_dot_enums_dot_pokemon__id__pb2._POKEMONID
_NPCPOKEMON.fields_by_name['pokemon_display'].message_type = pogoprotos_dot_data_dot_pokemon__display__pb2._POKEMONDISPLAY
DESCRIPTOR.message_types_by_name['NpcPokemon'] = _NPCPOKEMON

NpcPokemon = _reflection.GeneratedProtocolMessageType('NpcPokemon', (_message.Message,), dict(
  DESCRIPTOR = _NPCPOKEMON,
  __module__ = 'pogoprotos.data.npc_pokemon_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.NpcPokemon)
  ))
_sym_db.RegisterMessage(NpcPokemon)


# @@protoc_insertion_point(module_scope)
