# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/set_in_game_currency_exchange_rate_tracking.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/set_in_game_currency_exchange_rate_tracking.proto',
  package='pogoprotos.data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nApogoprotos/data/set_in_game_currency_exchange_rate_tracking.proto\x12\x0fpogoprotos.data\"\x98\x01\n%SetInGameCurrencyExchangeRateTracking\x12\x18\n\x10in_game_currency\x18\x01 \x01(\t\x12\x15\n\rfiat_currency\x18\x02 \x01(\t\x12.\n&fiat_currency_cost_e6_per_in_game_unit\x18\x03 \x01(\x03\x12\x0e\n\x06status\x18\x04 \x01(\tb\x06proto3')
)




_SETINGAMECURRENCYEXCHANGERATETRACKING = _descriptor.Descriptor(
  name='SetInGameCurrencyExchangeRateTracking',
  full_name='pogoprotos.data.SetInGameCurrencyExchangeRateTracking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='in_game_currency', full_name='pogoprotos.data.SetInGameCurrencyExchangeRateTracking.in_game_currency', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fiat_currency', full_name='pogoprotos.data.SetInGameCurrencyExchangeRateTracking.fiat_currency', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fiat_currency_cost_e6_per_in_game_unit', full_name='pogoprotos.data.SetInGameCurrencyExchangeRateTracking.fiat_currency_cost_e6_per_in_game_unit', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='pogoprotos.data.SetInGameCurrencyExchangeRateTracking.status', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=239,
)

DESCRIPTOR.message_types_by_name['SetInGameCurrencyExchangeRateTracking'] = _SETINGAMECURRENCYEXCHANGERATETRACKING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetInGameCurrencyExchangeRateTracking = _reflection.GeneratedProtocolMessageType('SetInGameCurrencyExchangeRateTracking', (_message.Message,), dict(
  DESCRIPTOR = _SETINGAMECURRENCYEXCHANGERATETRACKING,
  __module__ = 'pogoprotos.data.set_in_game_currency_exchange_rate_tracking_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.SetInGameCurrencyExchangeRateTracking)
  ))
_sym_db.RegisterMessage(SetInGameCurrencyExchangeRateTracking)


# @@protoc_insertion_point(module_scope)
