# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/user_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/user_events.proto',
  package='pogoprotos.data',
  syntax='proto3',
  serialized_pb=_b('\n!pogoprotos/data/user_events.proto\x12\x0fpogoprotos.data\"\x8d\x01\n\nUserEvents\x12\x14\n\x0c\x63\x61tch_streak\x18\x01 \x01(\x05\x12\x13\n\x0bspin_streak\x18\x02 \x01(\x05\x12%\n\x1d\x66ield_research_stamp_progress\x18\x03 \x01(\x05\x12\x10\n\x08level_up\x18\x04 \x01(\x05\x12\x1b\n\x13sent_friend_request\x18\x05 \x01(\x08\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USEREVENTS = _descriptor.Descriptor(
  name='UserEvents',
  full_name='pogoprotos.data.UserEvents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='catch_streak', full_name='pogoprotos.data.UserEvents.catch_streak', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spin_streak', full_name='pogoprotos.data.UserEvents.spin_streak', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field_research_stamp_progress', full_name='pogoprotos.data.UserEvents.field_research_stamp_progress', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level_up', full_name='pogoprotos.data.UserEvents.level_up', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sent_friend_request', full_name='pogoprotos.data.UserEvents.sent_friend_request', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=196,
)

DESCRIPTOR.message_types_by_name['UserEvents'] = _USEREVENTS

UserEvents = _reflection.GeneratedProtocolMessageType('UserEvents', (_message.Message,), dict(
  DESCRIPTOR = _USEREVENTS,
  __module__ = 'pogoprotos.data.user_events_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.UserEvents)
  ))
_sym_db.RegisterMessage(UserEvents)


# @@protoc_insertion_point(module_scope)
