# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/analytics/client_telemetry_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/analytics/client_telemetry_record.proto',
  package='pogoprotos.data.analytics',
  syntax='proto3',
  serialized_pb=_b('\n7pogoprotos/data/analytics/client_telemetry_record.proto\x12\x19pogoprotos.data.analytics\"s\n\x15\x43lientTelemetryRecord\x12\x11\n\trecord_id\x18\x01 \x01(\t\x12\x17\n\x0f\x65ncoded_message\x18\x02 \x01(\x0c\x12\x1b\n\x13\x63lient_timestamp_ms\x18\x03 \x01(\x03\x12\x11\n\tmetric_id\x18\x04 \x01(\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLIENTTELEMETRYRECORD = _descriptor.Descriptor(
  name='ClientTelemetryRecord',
  full_name='pogoprotos.data.analytics.ClientTelemetryRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record_id', full_name='pogoprotos.data.analytics.ClientTelemetryRecord.record_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encoded_message', full_name='pogoprotos.data.analytics.ClientTelemetryRecord.encoded_message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_timestamp_ms', full_name='pogoprotos.data.analytics.ClientTelemetryRecord.client_timestamp_ms', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metric_id', full_name='pogoprotos.data.analytics.ClientTelemetryRecord.metric_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['ClientTelemetryRecord'] = _CLIENTTELEMETRYRECORD

ClientTelemetryRecord = _reflection.GeneratedProtocolMessageType('ClientTelemetryRecord', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTELEMETRYRECORD,
  __module__ = 'pogoprotos.data.analytics.client_telemetry_record_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.analytics.ClientTelemetryRecord)
  ))
_sym_db.RegisterMessage(ClientTelemetryRecord)


# @@protoc_insertion_point(module_scope)
