# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/sfida/sfida_certification_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/sfida/sfida_certification_request.proto',
  package='pogoprotos.networking.requests.sfida',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nFpogoprotos/networking/requests/sfida/sfida_certification_request.proto\x12$pogoprotos.networking.requests.sfida\"\xde\x01\n\x19SfidaCertificationRequest\x12\x66\n\x05stage\x18\x01 \x01(\x0e\x32W.pogoprotos.networking.requests.sfida.SfidaCertificationRequest.SfidaCertificationStage\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"H\n\x17SfidaCertificationStage\x12\t\n\x05UNSET\x10\x00\x12\n\n\x06STAGE1\x10\x01\x12\n\n\x06STAGE2\x10\x02\x12\n\n\x06STAGE3\x10\x03\x62\x06proto3')
)



_SFIDACERTIFICATIONREQUEST_SFIDACERTIFICATIONSTAGE = _descriptor.EnumDescriptor(
  name='SfidaCertificationStage',
  full_name='pogoprotos.networking.requests.sfida.SfidaCertificationRequest.SfidaCertificationStage',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STAGE1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STAGE2', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STAGE3', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=263,
  serialized_end=335,
)
_sym_db.RegisterEnumDescriptor(_SFIDACERTIFICATIONREQUEST_SFIDACERTIFICATIONSTAGE)


_SFIDACERTIFICATIONREQUEST = _descriptor.Descriptor(
  name='SfidaCertificationRequest',
  full_name='pogoprotos.networking.requests.sfida.SfidaCertificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stage', full_name='pogoprotos.networking.requests.sfida.SfidaCertificationRequest.stage', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='pogoprotos.networking.requests.sfida.SfidaCertificationRequest.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SFIDACERTIFICATIONREQUEST_SFIDACERTIFICATIONSTAGE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=335,
)

_SFIDACERTIFICATIONREQUEST.fields_by_name['stage'].enum_type = _SFIDACERTIFICATIONREQUEST_SFIDACERTIFICATIONSTAGE
_SFIDACERTIFICATIONREQUEST_SFIDACERTIFICATIONSTAGE.containing_type = _SFIDACERTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['SfidaCertificationRequest'] = _SFIDACERTIFICATIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SfidaCertificationRequest = _reflection.GeneratedProtocolMessageType('SfidaCertificationRequest', (_message.Message,), dict(
  DESCRIPTOR = _SFIDACERTIFICATIONREQUEST,
  __module__ = 'pogoprotos.networking.requests.sfida.sfida_certification_request_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.sfida.SfidaCertificationRequest)
  ))
_sym_db.RegisterMessage(SfidaCertificationRequest)


# @@protoc_insertion_point(module_scope)
