# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/sfida/sfida_update_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.sfida import sfida_metrics_update_pb2 as pogoprotos_dot_data_dot_sfida_dot_sfida__metrics__update__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/sfida/sfida_update_request.proto',
  package='pogoprotos.networking.requests.sfida',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n?pogoprotos/networking/requests/sfida/sfida_update_request.proto\x12$pogoprotos.networking.requests.sfida\x1a\x30pogoprotos/data/sfida/sfida_metrics_update.proto\"\x7f\n\x12SfidaUpdateRequest\x12\x12\n\nplayer_lat\x18\x01 \x01(\x01\x12\x12\n\nplayer_lng\x18\x02 \x01(\x01\x12\x41\n\x0emetrics_update\x18\x03 \x01(\x0b\x32).pogoprotos.data.sfida.SfidaMetricsUpdateb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_sfida_dot_sfida__metrics__update__pb2.DESCRIPTOR,])




_SFIDAUPDATEREQUEST = _descriptor.Descriptor(
  name='SfidaUpdateRequest',
  full_name='pogoprotos.networking.requests.sfida.SfidaUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_lat', full_name='pogoprotos.networking.requests.sfida.SfidaUpdateRequest.player_lat', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_lng', full_name='pogoprotos.networking.requests.sfida.SfidaUpdateRequest.player_lng', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics_update', full_name='pogoprotos.networking.requests.sfida.SfidaUpdateRequest.metrics_update', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=282,
)

_SFIDAUPDATEREQUEST.fields_by_name['metrics_update'].message_type = pogoprotos_dot_data_dot_sfida_dot_sfida__metrics__update__pb2._SFIDAMETRICSUPDATE
DESCRIPTOR.message_types_by_name['SfidaUpdateRequest'] = _SFIDAUPDATEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SfidaUpdateRequest = _reflection.GeneratedProtocolMessageType('SfidaUpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _SFIDAUPDATEREQUEST,
  __module__ = 'pogoprotos.networking.requests.sfida.sfida_update_request_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.sfida.SfidaUpdateRequest)
  ))
_sym_db.RegisterMessage(SfidaUpdateRequest)


# @@protoc_insertion_point(module_scope)
