# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/sfida/sfida_capture_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import encounter_type_pb2 as pogoprotos_dot_enums_dot_encounter__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/sfida/sfida_capture_request.proto',
  package='pogoprotos.networking.requests.sfida',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n@pogoprotos/networking/requests/sfida/sfida_capture_request.proto\x12$pogoprotos.networking.requests.sfida\x1a%pogoprotos/enums/encounter_type.proto\"\xc5\x01\n\x13SfidaCaptureRequest\x12\x15\n\rspawnpoint_id\x18\x01 \x01(\t\x12\x14\n\x0c\x65ncounter_id\x18\x02 \x01(\x03\x12\x12\n\nplayer_lat\x18\x03 \x01(\x01\x12\x12\n\nplayer_lng\x18\x04 \x01(\x01\x12\x37\n\x0e\x65ncounter_type\x18\x05 \x01(\x0e\x32\x1f.pogoprotos.enums.EncounterType\x12\x0f\n\x07gym_lat\x18\x06 \x01(\x01\x12\x0f\n\x07gym_lng\x18\x07 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[pogoprotos_dot_enums_dot_encounter__type__pb2.DESCRIPTOR,])




_SFIDACAPTUREREQUEST = _descriptor.Descriptor(
  name='SfidaCaptureRequest',
  full_name='pogoprotos.networking.requests.sfida.SfidaCaptureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spawnpoint_id', full_name='pogoprotos.networking.requests.sfida.SfidaCaptureRequest.spawnpoint_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encounter_id', full_name='pogoprotos.networking.requests.sfida.SfidaCaptureRequest.encounter_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_lat', full_name='pogoprotos.networking.requests.sfida.SfidaCaptureRequest.player_lat', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_lng', full_name='pogoprotos.networking.requests.sfida.SfidaCaptureRequest.player_lng', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encounter_type', full_name='pogoprotos.networking.requests.sfida.SfidaCaptureRequest.encounter_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gym_lat', full_name='pogoprotos.networking.requests.sfida.SfidaCaptureRequest.gym_lat', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gym_lng', full_name='pogoprotos.networking.requests.sfida.SfidaCaptureRequest.gym_lng', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=343,
)

_SFIDACAPTUREREQUEST.fields_by_name['encounter_type'].enum_type = pogoprotos_dot_enums_dot_encounter__type__pb2._ENCOUNTERTYPE
DESCRIPTOR.message_types_by_name['SfidaCaptureRequest'] = _SFIDACAPTUREREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SfidaCaptureRequest = _reflection.GeneratedProtocolMessageType('SfidaCaptureRequest', (_message.Message,), dict(
  DESCRIPTOR = _SFIDACAPTUREREQUEST,
  __module__ = 'pogoprotos.networking.requests.sfida.sfida_capture_request_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.sfida.SfidaCaptureRequest)
  ))
_sym_db.RegisterMessage(SfidaCaptureRequest)


# @@protoc_insertion_point(module_scope)
